import { Context } from 'koishi';
import { ActiveLinkService } from '../service';
export declare class ActivityIdleTrigger {
    private ctx;
    private config;
    private service;
    private sessions;
    private conversationStates;
    private messageTimestamps;
    private chatMessages;
    private activityScorer;
    private adapterManager;
    private stateFilePath;
    private imageCacheDir;
    private dirty;
    private isSaving;
    private pendingSave;
    private readonly MAX_MESSAGES;
    private readonly MAX_TIMESTAMPS;
    constructor(ctx: Context, config: any, service: ActiveLinkService);
    start(): Promise<void>;
    stop(): Promise<void>;
    private handleMessage;
    private evaluateTriggers;
    private triggerResponse;
    private getProfileBySession;
    private getConversationId;
    private getOrCreateState;
    private recordTimestamp;
    private addChatMessage;
    private ensureMessageBucket;
    private appendChatMessage;
    private normalizeMessageContent;
    private getRecentHistoryMessages;
    private formatHistory;
    private formatTimestamp;
    private buildRequestText;
    private shouldUseHistory;
    private getPromptTemplate;
    private buildTemplateVars;
    private renderTemplate;
    private formatDate;
    private updateStateAfterResponse;
    private isGroupProfile;
    private markDirty;
    private loadState;
    private saveState;
}
//# sourceMappingURL=activity-idle.d.ts.map